// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Data;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20250306235511_AddedDescription")]
    partial class AddedDescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TodoList.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 7, 0, 55, 10, 887, DateTimeKind.Local).AddTicks(9263),
                            Description = "Create a full CRUD API with proper error handling and documentation",
                            Status = 0,
                            Title = "Build a REST API in .NET"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 7, 0, 55, 10, 887, DateTimeKind.Local).AddTicks(9266),
                            Description = "Study Swagger/OpenAPI specifications and implementation",
                            Status = 0,
                            Title = "Learn What OpenAPI Is"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 7, 0, 55, 10, 887, DateTimeKind.Local).AddTicks(9269),
                            Description = "Putting out fires",
                            Status = 0,
                            Title = "Make sure it dosent crash and burn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
